### ISSUE TITLE
Add more modern/metro look to chamber site homepage, etc.

### ISSUE THREAD

**Issue by TheModdersDen** [TheModdersDen/wdd230#23]
# Add more modern/metro look to chamber site

## ToDo

- [x] Add logo/icon of weather to windchill section `HOMEPAGE`
- [x] Make page look less intense with the current color choices. `HOMEPAGE`
- [x] Make a better/more improved navbar `ALL PAGES`
- [x] Potentially put some background music (a radio station?) embedded into the site `HOMEPAGE`
- [x] Redesign logo for chamber site `ALL PAGES`
- [ ] Improve background (add a background image/video?) `HOMEPAGE/ALL`
- [ ] Add some more images/pictures `HOMEPAGE/ALL`
- [ ] Make a todo-list in the filesystem.
